spring.application.name=springboot

spring.datasource.username=social_q46c_user

spring.datasource.password=FiqVDUvlyteoPzAK8CN7UcNzRxD8w2Uz

spring.datasource.url=jdbc:postgresql://dpg-d6jsuq450q8c73aagft0-a.oregon-postgres.render.com/social_q46c?currentSchema=public&sslmode=require

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true